;;; To avoid creation of instances, prepend "//" to the object name
;;;     "Q//QPaintDevice"

(defparameter *quick-n-names*
  (list "QJSValue"
        "QJSValueIterator"
        "QQmlAbstractUrlInterceptor"
        "QQmlError"
        "QQmlImageProviderBase"
        "QQmlIncubationController"
        "QQmlIncubator"
        "QQmlNetworkAccessManagerFactory"
        "QQmlParserStatus"
        "QQmlProperty"
        "QQmlPropertyValueSource"
        "QQmlScriptString"
        "QQuickAsyncImageProvider"
        "QQuickImageProvider"
        "QSGBasicGeometryNode"
        "QSGClipNode"
        "QSGFlatColorMaterial"
        "QSGGeometry"
        "QSGGeometryNode"
        "QSGMaterial"
        "//QSGMaterialShader"
        "QSGMaterialType"
        "QSGNode"
        "QSGOpacityNode"
        "QSGOpaqueTextureMaterial"
        "QSGSimpleRectNode"
        "QSGSimpleTextureNode"
        "QSGTextureMaterial"
        "QSGTransformNode"
        "QSGVertexColorMaterial"
        ))
