;;; To avoid creation of instances, prepend "//" to the object name
;;;     "//QClipboard"

(defparameter *quick-q-names*
  (list "QJSEngine"
        "QQmlApplicationEngine"
        "QQmlComponent"
        "QQmlContext"
        "QQmlEngine"
        "QQmlExpression"
        "QQmlExtensionPlugin"
        "QQmlFileSelector"
        "QQmlPropertyMap"
        "//QQuickFramebufferObject"
        "QQuickImageResponse"
        "QQuickItem"
        "QQuickItemGrabResult"
        "QQuickPaintedItem"
        "QQuickRenderControl"
        "QQuickTextDocument"
        "QQuickTextureFactory"
        "QQuickView"
        "QQuickWidget"
        "QQuickWindow"
        "QSGAbstractRenderer"
        "QSGDynamicTexture"
        "QSGEngine"
        "QSGTexture"
        "QSGTextureProvider"
        ))

