(defpackage :eql
  (:export
   #:|dir|
   #:|disableAttributeArray(const char*)|
   #:|disableAttributeArray(int)|
   #:|disableAttributeArray|
   #:|discardCommand|
   #:|disconnectFromHost|
   #:|disconnectFromServer|
   #:|disconnected|
   #:|display(QString)|
   #:|display(double)|
   #:|display(int)|
   #:|displayColumn|
   #:|displayFormat|
   #:|displayIntegerBase|
   #:|displayName(QDateTime)|
   #:|displayName(QDateTime...)|
   #:|displayName(QTimeZone::TimeType)|
   #:|displayName(QTimeZone::TimeType...)|
   #:|displayName.QStandardPaths|
   #:|displayName|
   #:|displayText|
   #:|displayedSections|
   #:|display|
   #:|distanceToLine|
   #:|distanceToPlane|
   #:|distanceToPoint|
   #:|doAction|
   #:|doItemsLayout|
   #:|docName|
   #:|dockLocationChanged|
   #:|dockOptions|
   #:|dockWidgetArea|
   #:|documentElement|
   #:|documentLayoutChanged|
   #:|documentLayout|
   #:|documentMargin|
   #:|documentMode|
   #:|documentSizeChanged|
   #:|documentSize|
   #:|documentTitle|
   #:|documentationFileName|
   #:|document|
   #:|domain|
   #:|doneCurrent|
   #:|done|
   #:|dotProduct.QQuaternion|
   #:|dotProduct.QVector2D|
   #:|dotProduct.QVector3D|
   #:|dotProduct.QVector4D|
   #:|dotsPerMeterX|
   #:|dotsPerMeterY|
   #:|doubleClickInterval.QApplication|
   #:|doubleClicked|
   #:|doubleDecimals|
   #:|doubleMaximum|
   #:|doubleMinimum|
   #:|doubleProperty|
   #:|doubleValueChanged|
   #:|doubleValueSelected|
   #:|doubleValue|
   #:|downloadProgress|
   #:|downloadRequested|
   #:|dragCursor|
   #:|dragDropMode|
   #:|dragDropOverwriteMode|
   #:|dragEnabled|
   #:|dragMode|
   #:|drawArc(QRect...)|
   #:|drawArc(QRectF...)|
   #:|drawArc|
   #:|drawBackground|
   #:|drawBase|
   #:|drawChord(QRect...)|
   #:|drawChord(QRectF...)|
   #:|drawChord|
   #:|drawComplexControl|
   #:|drawContents|
   #:|drawControl|
   #:|drawConvexPolygon(QPolygon)|
   #:|drawConvexPolygon(QPolygonF)|
   #:|drawConvexPolygon|
   #:|drawCursor|
   #:|drawEllipse(QPoint...)|
   #:|drawEllipse(QPointF...)|
   #:|drawEllipse(QRect)|
   #:|drawEllipse(QRectF)|
   #:|drawEllipse|
   #:|drawGlyphRun|
   #:|drawImage(QPoint...)|
   #:|drawImage(QPointF...)|
   #:|drawImage(QRect...)|
   #:|drawImage(QRectF...)|
   #:|drawImage(int...)|
   #:|drawImage|
   #:|drawItemPixmap|
   #:|drawItemText|
   #:|drawLine(QLine)|
   #:|drawLine(QLineF)|
   #:|drawLine(QPoint...)|
   #:|drawLine(QPointF...)|
   #:|drawLines(QVector<QLine>)|
   #:|drawLines(QVector<QLineF>)|
   #:|drawLines(QVector<QPoint>)|
   #:|drawLines(QVector<QPointF>)|
   #:|drawLines(const QLine*...)|
   #:|drawLines(const QLineF*...)|
   #:|drawLines(const QPointF*...)|
   #:|drawLines|
   #:|drawLine|
   #:|drawPath|
   #:|drawPicture(QPoint...)|
   #:|drawPicture(QPointF...)|
   #:|drawPicture|
   #:|drawPie(QRect...)|
   #:|drawPie(QRectF...)|
   #:|drawPie|
   #:|drawPixmap(QPoint...)|
   #:|drawPixmap(QPointF...)|
   #:|drawPixmap(QRect...)|
   #:|drawPixmap(QRectF...)|
   #:|drawPixmap(int...)|
   #:|drawPixmapFragments|
   #:|drawPixmap|
   #:|drawPoint(QPoint)|
   #:|drawPoint(QPointF)|
   #:|drawPoints(QPolygon)|
   #:|drawPoints(QPolygonF)|
   #:|drawPoints|
   #:|drawPoint|
   #:|drawPolygon(QPolygon)|
   #:|drawPolygon(QPolygon...)|
   #:|drawPolygon(QPolygonF)|
   #:|drawPolygon(QPolygonF...)|
   #:|drawPolygon(const QPointF*...)|
   #:|drawPolygon|
   #:|drawPolyline(QPolygon)|
   #:|drawPolyline(QPolygonF)|
   #:|drawPolyline|
   #:|drawPrimitive|
   #:|drawRect(QRect)|
   #:|drawRect(QRectF)|
   #:|drawRects(QVector<QRect>)|
   #:|drawRects(QVector<QRectF>)|
   #:|drawRects(const QRect*...)|
   #:|drawRects(const QRectF*...)|
   #:|drawRects|
   #:|drawRect|
   #:|drawRoundedRect(QRect...)|
   #:|drawRoundedRect(QRectF...)|
   #:|drawRoundedRect|
   #:|drawSource|
   #:|drawStaticText(QPoint...)|
   #:|drawStaticText(QPointF...)|
   #:|drawStaticText|
   #:|drawText(QPoint...)|
   #:|drawText(QPointF...)|
   #:|drawText(QRect...)|
   #:|drawText(QRectF,QString...)|
   #:|drawText(QRectF,int...)|
   #:|drawText(QRectF...)|
   #:|drawText(int...)|
   #:|drawText|
   #:|drawTiledPixmap(QRect...)|
   #:|drawTiledPixmap(QRectF...)|
   #:|drawTiledPixmap|
   #:|drawTree|
   #:|drawingMode|
   #:|draw|
   #:|driverName|
   #:|driverText|
   #:|drivers.QSqlDatabase|
   #:|driver|
   #:|drives.QDir|
   #:|dropAction|
   #:|dropEvent|
   #:|dropIndicatorPosition|
   #:|dropMimeData|
   #:|dumpObjectInfo|
   #:|dumpObjectTree|
   #:|duplex|
   #:|duplicatesEnabled|
   #:|durationChanged|
   #:|durationForBytes|
   #:|durationForFrames|
   #:|duration|
   #:|dx|
   #:|dynamicPropertyNames|
   #:|dynamicSortFilter|
   #:|dy|
   #:|easingCurve|
   #:|echoMode|
   #:|editItem|
   #:|editStrategy|
   #:|editTextChanged|
   #:|editTriggers|
   #:|editingFinished|
   #:|editorDestroyed|
   #:|editorEvent|
   #:|edit|
   #:|effectiveDate|
   #:|effectiveDevicePixelRatio|
   #:|effectiveOpacity|
   #:|effectiveSizeHint|
   #:|effectiveWinId|
   #:|elapsedUSecs|
   #:|elapsed|
   #:|elementCount|
   #:|elementExists|
   #:|elementId|
   #:|element|
   #:|elideMode|
   #:|elidedText|
   #:|ellipticCurves|
   #:|emitDataChanged|
   #:|emitSelectionChanged|
   #:|emptyLabel|
   #:|enableAttributeArray(const char*)|
   #:|enableAttributeArray(int)|
   #:|enableAttributeArray|
   #:|enablePersistentStorage.QWebSettings|
   #:|enabledChanged|
   #:|encloseContentsWith(QString)|
   #:|encloseContentsWith(QWebElement)|
   #:|encloseContentsWith|
   #:|encloseWith(QString)|
   #:|encloseWith(QWebElement)|
   #:|encloseWith|
   #:|enclosingBlockElement|
   #:|encodeName.QFile|
   #:|encodingMode|
   #:|encodingOption|
   #:|encodingSettings|
   #:|encrypted|
   #:|encryptionMethod|
   #:|endArray|
   #:|endEditBlock|
   #:|endFrame|
   #:|endGroup|
   #:|endInsertColumns|
   #:|endInsertRows|
   #:|endLayout|
   #:|endMacro|
   #:|endMoveColumns|
   #:|endMoveRows|
   #:|endNativePainting|
   #:|endPaint|
   #:|endRemoveColumns|
   #:|endRemoveRows|
   #:|endResetModel|
   #:|endTime|
   #:|endValue|
   #:|end|
   #:|engine|
   #:|ensureActiveTarget|
   #:|ensureBlockLayout|
   #:|ensureCursorVisible|
   #:|ensurePolished|
   #:|ensureVisible(QRectF)|
   #:|ensureVisible(QRectF...)|
   #:|ensureVisible(const QGraphicsItem*)|
   #:|ensureVisible(const QGraphicsItem*...)|
   #:|ensureVisible|
   #:|ensureWidgetVisible|
   #:|enterWhatsThisMode.QWhatsThis|
   #:|entered|
   #:|entryInfoList(QDir::Filters)|
   #:|entryInfoList(QDir::Filters...)|
   #:|entryInfoList(QStringList)|
   #:|entryInfoList(QStringList...)|
   #:|entryInfoList|
   #:|entryList(QDir::Filters)|
   #:|entryList(QDir::Filters...)|
   #:|entryList(QStringList)|
   #:|entryList(QStringList...)|
   #:|entryList|
   #:|enumeratorCount|
   #:|enumeratorOffset|
   #:|equals|
   #:|eraseRect(QRect)|
   #:|eraseRect(QRectF)|
   #:|eraseRect|
   #:|errorStateChanged|
   #:|errorState|
   #:|errorString|
   #:|errors|
   #:|error|
   #:|escape.QRegExp|
   #:|escape.QRegularExpression|
   #:|escapeButton|
   #:|escapeIdentifier|
   #:|evaluateJavaScript|
   #:|evaluate|
   #:|eventDispatcher.QCoreApplication|
   #:|eventFilter|
   #:|eventSource|
   #:|eventType|
   #:|event|
   #:|exactMatch|
   #:|exclusive|
   #:|exec.QApplication|
   #:|exec.QCoreApplication|
   #:|exec.QGuiApplication|
   #:|exec.QMenu|
   #:|execBatch|
   #:|execute.QProcess|
   #:|executeDelayedItemsLayout|
   #:|executedQuery|
   #:|exec|
   #:|exists.QFileInfo|
   #:|exists.QFile|
   #:|exists|
   #:|exit.QCoreApplication|
   #:|exitCode|
   #:|exitStatus|
   #:|exited|
   #:|exit|
   #:|expandAll|
   #:|expandExtendedSearch|
   #:|expandItem|
   #:|expandToDepth|
   #:|expanded|
   #:|expandingDirections|
   #:|expanding|
   #:|expandsOnDoubleClick|
   #:|expand|
   #:|expectedSize|
   #:|expirationDate|
   #:|expiryDate|
   #:|exponential|
   #:|exposeEvent|
   #:|exposureCompensationChanged|
   #:|exposureCompensation|
   #:|exposureMode|
   #:|exposure|
   #:|expression|
   #:|extensions|
   #:|extension|
   #:|extraSelections|
   #:|extraSelectors|
   #:|faces|
   #:|fallbacksEnabled|
   #:|families|
   #:|family|
   #:|featurePermissionRequestCanceled|
   #:|featurePermissionRequested|
   #:|featuresChanged|
   #:|features|
   #:|fetchMore|
   #:|field(QString)|
   #:|field(int)|
   #:|fieldGrowthPolicy|
   #:|fieldIndex|
   #:|fieldName|
   #:|fieldType|
   #:|field|
   #:|fileChanged|
   #:|fileData|
   #:|fileIcon|
   #:|fileInfo|
   #:|fileMetaData|
   #:|fileMode|
   #:|fileName|
   #:|filePath|
   #:|fileRenamed|
   #:|fileSelected|
   #:|fileSystemType|
   #:|filesSelected|
   #:|files|
   #:|file|
   #:|fill(QColor)|
   #:|fill(Qt::GlobalColor)|
   #:|fill(uint)|
   #:|fillColorChanged|
   #:|fillColor|
   #:|fillPath|
   #:|fillRect(QRect,QBrush)|
   #:|fillRect(QRect,QColor)|
   #:|fillRect(QRect,Qt::BrushStyle)|
   #:|fillRect(QRect,Qt::GlobalColor)|
   #:|fillRect(QRect...)|
   #:|fillRect(QRectF,QBrush)|
   #:|fillRect(QRectF,QColor)|
   #:|fillRect(QRectF,Qt::BrushStyle)|
   #:|fillRect(QRectF,Qt::GlobalColor)|
   #:|fillRect(QRectF...)|
   #:|fillRect(int,int,int,int,QBrush)|
   #:|fillRect(int,int,int,int,QColor)|
   #:|fillRect(int,int,int,int,Qt::BrushStyle)|
   #:|fillRect(int,int,int,int,Qt::GlobalColor)|
   #:|fillRect|
   #:|fillRule|
   #:|fill|
   #:|filterAttributeSets|
   #:|filterAttributes|
   #:|filterCaseSensitivity|
   #:|filterIndices|
   #:|filterKeyColumn|
   #:|filterMode|
   #:|filterRegExp|
   #:|filterRole|
   #:|filterSelected|
   #:|filtering|
   #:|filtersChildEvents|
   #:|filtersChildMouseEvents|
   #:|filter|
   #:|finalStop|
   #:|find(QRegExp)|
   #:|find(QRegExp,QTextCursor)|
   #:|find(QRegExp,QTextCursor...)|
   #:|find(QRegExp,int)|
   #:|find(QRegExp,int...)|
   #:|find(QRegExp...)|
   #:|find(QRegularExpression)|
   #:|find(QRegularExpression,QTextCursor)|
   #:|find(QRegularExpression,QTextCursor...)|
   #:|find(QRegularExpression,int)|
   #:|find(QRegularExpression,int...)|
   #:|find(QRegularExpression...)|
   #:|find(QString)|
   #:|find(QString,QTextCursor)|
   #:|find(QString,QTextCursor...)|
   #:|find(QString,int)|
   #:|find(QString,int...)|
   #:|find(QString...)|
   #:|find.QPixmapCache|
   #:|find.QWidget|
   #:|findAllElements|
   #:|findAll|
   #:|findBlockByLineNumber|
   #:|findBlockByNumber|
   #:|findBlock|
   #:|findBufferChanged|
   #:|findData|
   #:|findExecutable.QStandardPaths|
   #:|findFile|
   #:|findFirstElement|
   #:|findFirst|
   #:|findItems|
   #:|findText|
   #:|find|
   #:|finished|
   #:|finish|
   #:|firstBlock|
   #:|firstChild|
   #:|firstCursorPosition|
   #:|firstDayOfWeek|
   #:|firstLineNumber|
   #:|firstPosition|
   #:|firstVisibleBlock|
   #:|first|
   #:|fitInView(QRectF)|
   #:|fitInView(QRectF...)|
   #:|fitInView(const QGraphicsItem*)|
   #:|fitInView(const QGraphicsItem*...)|
   #:|fitInView|
   #:|fitToWidth|
   #:|fixedPitch|
   #:|fixup|
   #:|flags|
   #:|flashMode|
   #:|flashReady|
   #:|flow|
   #:|flush.QCoreApplication|
   #:|flush|
   #:|focalPoint|
   #:|focalRadius|
   #:|focusChanged|
   #:|focusChild|
   #:|focusInEvent|
   #:|focusItemChanged|
   #:|focusItem|
   #:|focusMode|
   #:|focusNextChild|
   #:|focusNextPrevChild|
   #:|focusObject.QGuiApplication|
   #:|focusObjectChanged|
   #:|focusObject|
   #:|focusOutEvent|
   #:|focusPointMode|
   #:|focusPolicy|
   #:|focusPreviousChild|
   #:|focusProxy|
   #:|focusWidget.QApplication|
   #:|focusWidget|
   #:|focusWindow.QGuiApplication|
   #:|focusWindowChanged|
   #:|focusZonesChanged|
   #:|focusZones|
   #:|focus|
   #:|font(const QWidget*).QApplication|
   #:|font(const char*).QApplication|
   #:|font.QApplication|
   #:|font.QGuiApplication|
   #:|font.QToolTip|
   #:|fontCapitalization|
   #:|fontDatabaseChanged|
   #:|fontEmbeddingEnabled|
   #:|fontFamily|
   #:|fontFilters|
   #:|fontFixedPitch|
   #:|fontHintingPreference|
   #:|fontInfo|
   #:|fontItalic|
   #:|fontKerning|
   #:|fontLetterSpacingType|
   #:|fontLetterSpacing|
   #:|fontMetrics.QApplication|
   #:|fontMetrics|
   #:|fontOverline|
   #:|fontPointSize|
   #:|fontSelected|
   #:|fontSize|
   #:|fontSmoothingGamma|
   #:|fontStretch|
   #:|fontStrikeOut|
   #:|fontStyleHint|
   #:|fontStyleStrategy|
   #:|fontUnderline|
   #:|fontWeight|
   #:|fontWordSpacing|
   #:|font|
   #:|forceActiveFocus|
   #:|forceCompletion|
   #:|forcePolish|
   #:|forceShow|
   #:|foregroundBrush|
   #:|foregroundColor|
   #:|foregroundRole|
   #:|foreground|
   #:|formAlignment|
   #:|formatIndex|
   #:|formatValue|
   #:|formats|
   #:|format|
   #:|forwardAvailable|
   #:|forwardHistoryCount|
   #:|forwardUnsupportedContent|
   #:|forward|
   #:|fragment|
   #:|frameAt|
   #:|frameBoundingRect|
   #:|frameChanged|
   #:|frameCount|
   #:|frameCreated|
   #:|frameForTime|
   #:|frameFormat|
   #:|frameGeometry|
   #:|frameHeight|
   #:|frameMargins|
   #:|frameName|
   #:|framePosition|
   #:|frameRate|
   #:|frameRect|
   #:|frameShadow|
   #:|frameShape|
   #:|frameSize|
   #:|frameStyle|
   #:|frameSwapped|
   #:|frameWidth|
   #:|framesForBytes|
   #:|framesForDuration|
   #:|framesPerSecond|
   #:|frame|
   #:|frequencyChanged|
   #:|frequencyStep|
   #:|frequency|
   #:|fromAce.QUrl|
   #:|fromAxes.QQuaternion|
   #:|fromAxisAndAngle.QQuaternion|
   #:|fromCmyk.QColor|
   #:|fromCmykF.QColor|
   #:|fromData.QImage|
   #:|fromData.QSslCertificate|
   #:|fromDirection.QQuaternion|
   #:|fromEncoded.QUrl|
   #:|fromEulerAngles.QQuaternion|
   #:|fromHsl.QColor|
   #:|fromHslF.QColor|
   #:|fromHsv.QColor|
   #:|fromHsvF.QColor|
   #:|fromHtml.QTextDocumentFragment|
   #:|fromImage.QBitmap|
   #:|fromImage.QPixmap|
   #:|fromImageReader.QPixmap|
   #:|fromJulianDay.QDate|
   #:|fromLocalFile.QUrl|
   #:|fromMSecsSinceEpoch(qlonglong,QTimeZone).QDateTime|
   #:|fromMSecsSinceEpoch(qlonglong,Qt::TimeSpec).QDateTime|
   #:|fromMSecsSinceEpoch.QDateTime|
   #:|fromMSecsSinceStartOfDay.QTime|
   #:|fromName.QHostInfo|
   #:|fromNativeSeparators.QDir|
   #:|fromPage|
   #:|fromPath.QSslCertificate|
   #:|fromPercentEncoding.QUrl|
   #:|fromPlainText.QTextDocumentFragment|
   #:|fromRfc4122.QUuid|
   #:|fromRgb.QColor|
   #:|fromRgbF.QColor|
   #:|fromRgba.QColor|
   #:|fromScale.QTransform|
   #:|fromString(QString,QString).QDateTime|
   #:|fromString(QString,QString).QDate|
   #:|fromString(QString,QString).QTime|
   #:|fromString(QString,Qt::DateFormat).QDateTime|
   #:|fromString(QString,Qt::DateFormat).QDate|
   #:|fromString(QString,Qt::DateFormat).QTime|
   #:|fromString.QDateTime|
   #:|fromString.QDate|
   #:|fromString.QKeySequence|
   #:|fromString.QTime|
   #:|fromStringList.QUrl|
   #:|fromString|
   #:|fromTheme.QIcon|
   #:|fromTime_t(uint,QTimeZone).QDateTime|
   #:|fromTime_t(uint,Qt::TimeSpec).QDateTime|
   #:|fromTime_t.QDateTime|
   #:|fromTranslate.QTransform|
   #:|fromUnicode|
   #:|fromUserInput.QUrl|
   #:|fromWinId.QWindow|
   #:|frustum|
   #:|fullPage|
   #:|fullRectPixels|
   #:|fullRectPoints|
   #:|fullRect|
   #:|fullScreenChanged|
   #:|fullServerName|
   #:|functions|
   #:|generateMipMaps|
   #:|generatedIconPixmap|
   #:|geometriesChanged|
   #:|geometryChangeRequested|
   #:|geometryChanged|
   #:|geometry|
   #:|gestureCancelPolicy|
   #:|gestureType|
   #:|gestures|
   #:|gesture|
   #:|get.QQmlFileSelector|
   #:|getChar|
   #:|getColor.QColorDialog|
   #:|getDouble.QInputDialog|
   #:|getExistingDirectory.QFileDialog|
   #:|getExistingDirectoryUrl.QFileDialog|
   #:|getFont(bool*,QFont).QFontDialog|
   #:|getFont(bool*,QWidget*).QFontDialog|
   #:|getFont.QFontDialog|
   #:|getInt.QInputDialog|
   #:|getItem.QInputDialog|
   #:|getMultiLineText.QInputDialog|
   #:|getOpenFileName.QFileDialog|
   #:|getOpenFileNames.QFileDialog|
   #:|getOpenFileUrl.QFileDialog|
   #:|getOpenFileUrls.QFileDialog|
   #:|getProcAddress|
   #:|getSaveFileName.QFileDialog|
   #:|getSaveFileUrl.QFileDialog|
   #:|getText.QInputDialog|
   #:|get|
   #:|globalMatch(QString)|
   #:|globalMatch(QString...)|
   #:|globalMatch(QStringRef)|
   #:|globalMatch(QStringRef...)|
   #:|globalMatch|
   #:|globalObject|
   #:|globalPosF|
   #:|globalPos|
   #:|globalRestorePolicy|
   #:|globalSettings.QWebSettings|
   #:|globalShareContext.QOpenGLContext|
   #:|globalStrut.QApplication|
   #:|globalX|
   #:|globalY|
   #:|glyphRuns|
   #:|gotFocus|
   #:|grabFramebuffer|
   #:|grabGesture|
   #:|grabKeyboard|
   #:|grabMouse|
   #:|grabShortcut|
   #:|grabTouchPoints|
   #:|grabWindow|
   #:|grab|
   #:|gradient|
   #:|graphicsEffect|
   #:|graphicsItem|
   #:|graphicsProxyWidget|
   #:|greenBufferSize|
   #:|greenF|
   #:|green|
   #:|gridSize|
   #:|gridStyle|
   #:|groupId|
   #:|groupSeparator|
   #:|group|
   #:|handleWidth|
   #:|handle|
   #:|hardwareAddress|
   #:|hasAcceptableInput|
   #:|hasActiveFocus|
   #:|hasAlphaChannel|
   #:|hasAlpha|
   #:|hasAttributeNS|
   #:|hasAttributes|
   #:|hasAttribute|
   #:|hasAutoScroll|
   #:|hasChildren|
   #:|hasClass|
   #:|hasClipping|
   #:|hasColor|
   #:|hasComplexSelection|
   #:|hasCursor|
   #:|hasDaylightTime|
   #:|hasDefaultAlphaBuffer.QQuickWindow|
   #:|hasError|
   #:|hasExpired|
   #:|hasExtension|
   #:|hasFeature.QOpenGLTexture|
   #:|hasFeature|
   #:|hasFocus|
   #:|hasFormat|
   #:|hasFragment|
   #:|hasFrame|
   #:|hasHeightForWidth|
   #:|hasHotSpot|
   #:|hasHtml|
   #:|hasImage|
   #:|hasIndex|
   #:|hasMipmaps|
   #:|hasMouseTracking|
   #:|hasNext|
   #:|hasNotifySignal|
   #:|hasOpenGLFramebufferBlit.QOpenGLFramebufferObject|
   #:|hasOpenGLFramebufferObjects.QOpenGLFramebufferObject|
   #:|hasOpenGLShaderPrograms.QOpenGLShaderProgram|
   #:|hasOpenGLShaders.QOpenGLShader|
   #:|hasOutValues|
   #:|hasOwnProperty|
   #:|hasPendingConnections|
   #:|hasPendingDatagrams|
   #:|hasProperty|
   #:|hasQuery|
   #:|hasRawHeader|
   #:|hasSameIdentifier|
   #:|hasScaledContents|
   #:|hasSelectedText|
   #:|hasSelection|
   #:|hasStaticContents|
   #:|hasSupport.QMediaPlayer|
   #:|hasText|
   #:|hasThemeIcon.QIcon|
   #:|hasTracking|
   #:|hasTransitions|
   #:|hasUrls|
   #:|hasVisitedPage|
   #:|hasWidthForHeight|
   #:|hash.QCryptographicHash|
   #:|hash.QMessageAuthenticationCode|
   #:|headerDataChanged|
   #:|headerData|
   #:|headerItem|
   #:|headerRowCount|
   #:|headerTextFormat|
   #:|header|
   #:|head|
   #:|heightChanged|
   #:|heightForWidth|
   #:|heightMM|
   #:|heightValid|
   #:|height|
   #:|helpEvent|
   #:|helpRequested|
   #:|hiResGlobalX|
   #:|hiResGlobalY|
   #:|hiddenSectionCount|
   #:|hideColumn|
   #:|hideEvent|
   #:|hideOrShow|
   #:|hidePopup|
   #:|hideRow|
   #:|hideSection|
   #:|hideTearOffMenu|
   #:|hideText.QToolTip|
   #:|hideText.QWhatsThis|
   #:|hide|
   #:|highlightSections|
   #:|highlighted(QModelIndex)|
   #:|highlighted(QString)|
   #:|highlighted(QUrl)|
   #:|highlighted(int)|
   #:|highlightedText|
   #:|highlighted|
   #:|highlight|
   #:|hintingPreference|
   #:|historyChanged|
   #:|historyContains|
   #:|historyTitle|
   #:|historyTypeChanged|
   #:|historyType|
   #:|historyUrl|
   #:|history|
   #:|hitCount|
   #:|hitTestComplexControl|
   #:|hitTestContent|
   #:|hitTestPath|
   #:|hitTest|
   #:|home.QDir|
   #:|homePath.QDir|
   #:|home|
   #:|horizontalAdvance|
   #:|horizontalDirection|
   #:|horizontalHeaderFormat|
   #:|horizontalHeaderItem|
   #:|horizontalHeader|
   #:|horizontalPolicy|
   #:|horizontalScrollBarPolicy|
   #:|horizontalScrollBar|
   #:|horizontalScrollMode|
   #:|horizontalScrollbarAction|
   #:|horizontalScrollbarValueChanged|
   #:|horizontalSpacing|
   #:|horizontalStretch|
   #:|horizontalWrapMode|
   #:|hostFound|
   #:|hostName|
   #:|host|
   #:|hotSpot|
   #:|hour|
   #:|hovered|
   #:|hover|
   #:|href|
   #:|hslHueF|
   #:|hslHue|
   #:|hslSaturationF|
   #:|hslSaturation|
   #:|hsvHueF|
   #:|hsvHue|
   #:|hsvSaturationF|
   #:|hsvSaturation|
   #:|html|
   #:|hueChanged|
   #:|hueF|
   #:|hue|
   #:|humanReadableName|
   #:|ianaIdToWindowsId.QTimeZone|
   #:|icon(QFileIconProvider::IconType)|
   #:|icon(QFileInfo)|
   #:|iconChanged|
   #:|iconDatabasePath.QWebSettings|
   #:|iconForUrl.QWebSettings|
   #:|iconPixmap|
   #:|iconProvider|
   #:|iconSizeChanged|
   #:|iconSize|
   #:|iconText|
   #:|icon|
   #:|id(QSize).QPageSize|
   #:|id(QSize...).QPageSize|
   #:|id(QSizeF...).QPageSize|
   #:|id(int).QPageSize|
   #:|id.QPageSize|
   #:|idealWidth|
   #:|identifier|
   #:|idnWhitelist.QUrl|
   #:|id|
   #:|ignore(QGesture*)|
   #:|ignore(Qt::GestureType)|
   #:|ignoreSslErrors|
   #:|ignore|
   #:|imageAvailable|
   #:|imageCaptured|
   #:|imageCodecDescription|
   #:|imageData|
   #:|imageExposed|
   #:|imageFormatFromPixelFormat.QVideoFrame|
   #:|imageMetadataAvailable|
   #:|imageProcessing|
   #:|imageProvider|
   #:|imageSaved|
   #:|imageType|
   #:|imageUrl|
   #:|image|
   #:|implicitHeightChanged|
   #:|implicitHeight|
   #:|implicitWidthChanged|
   #:|implicitWidth|
   #:|importPathList|
   #:|importPlugin|
   #:|inFontUcs4|
   #:|inFont|
   #:|inWhatsThisMode.QWhatsThis|
   #:|incubateFor|
   #:|incubatingObjectCount|
   #:|incubationController|
   #:|incubationMode|
   #:|indentWidth|
   #:|indentation|
   #:|indent|
   #:|index(QString...)|
   #:|index(int...)|
   #:|indexAbove|
   #:|indexAt|
   #:|indexBelow|
   #:|indexChanged|
   #:|indexColumn|
   #:|indexCount|
   #:|indexCreated|
   #:|indexCreationStarted|
   #:|indexDataAsUShort|
   #:|indexDataPattern|
   #:|indexDocumentation|
   #:|indexFromItem|
   #:|indexIn|
   #:|indexOfAnimation|
   #:|indexOfChild|
   #:|indexOfClassInfo|
   #:|indexOfConstructor|
   #:|indexOfEnumerator|
   #:|indexOfMethod|
   #:|indexOfProperty|
   #:|indexOfSignal|
   #:|indexOfSlot|
   #:|indexOfTopLevelItem|
   #:|indexOf|
   #:|indexRowSizeHint|
   #:|indexType|
   #:|indexWidget|
   #:|indexesMoved|
   #:|indexes|
   #:|indexingFinished|
   #:|indexingStarted|
   #:|index|
   #:|information.QMessageBox|
   #:|informativeText|
   #:|inherits|
   #:|iniCodec|
   #:|initFrom|
   #:|initStyleOption|
   #:|initialLayoutCompleted|
   #:|initialSize|
   #:|initialStateChanged|
   #:|initialState|
   #:|initializeColumn|
   #:|initializeEngine|
   #:|initializePage|
   #:|initialize|
   #:|inputChannelMode|
   #:|inputDirectionChanged|
   #:|inputDirection|
   #:|inputItemRectangle|
   #:|inputItemTransform|
   #:|inputMask|
   #:|inputMethod.QGuiApplication|
   #:|inputMethodHints|
   #:|inputMethodQuery|
   #:|inputMode|
   #:|insert.QPixmapCache|
   #:|insertActions|
   #:|insertAction|
   #:|insertAnimation|
   #:|insertBlock|
   #:|insertChildNodeAfter|
   #:|insertChildNodeBefore|
   #:|insertChildren|
   #:|insertChild|
   #:|insertColumn(int,QList<QStandardItem*>)|
   #:|insertColumn(int,QModelIndex)|
   #:|insertColumns|
   #:|insertColumn|
   #:|insertContents|
   #:|insertCookie|
   #:|insertFragment|
   #:|insertFrame|
   #:|insertHtml|
   #:|insertImage(QImage)|
   #:|insertImage(QImage...)|
   #:|insertImage(QString)|
   #:|insertImage(QTextImageFormat)|
   #:|insertImage(QTextImageFormat...)|
   #:|insertImage|
   #:|insertIndices|
   #:|insertItem(int,QIcon...)|
   #:|insertItem(int,QListWidgetItem*)|
   #:|insertItem(int,QString)|
   #:|insertItem(int,QString...)|
   #:|insertItems|
   #:|insertItem|
   #:|insertLayout|
   #:|insertList(QTextListFormat)|
   #:|insertList(QTextListFormat::Style)|
   #:|insertList|
   #:|insertMedia(int,QList<QMediaContent>)|
   #:|insertMedia(int,QMediaContent)|
   #:|insertMedia|
   #:|insertMenu|
   #:|insertPause|
   #:|insertPermanentWidget|
   #:|insertPlainText|
   #:|insertPolicy|
   #:|insertRecord|
   #:|insertRow(int,QLayout*)|
   #:|insertRow(int,QList<QStandardItem*>)|
   #:|insertRow(int,QModelIndex)|
   #:|insertRow(int,QStandardItem*)|
   #:|insertRow(int,QString,QLayout*)|
   #:|insertRow(int,QString,QWidget*)|
   #:|insertRow(int,QString...)|
   #:|insertRow(int,QWidget*)|
   #:|insertRow(int,QWidget*,QLayout*)|
   #:|insertRow(int,QWidget*,QWidget*)|
   #:|insertRow(int,QWidget*...)|
   #:|insertRows(int,QList<QStandardItem*>)|
   #:|insertRows(int,int)|
   #:|insertRows|
   #:|insertRow|
   #:|insertSection|
   #:|insertSeparator|
   #:|insertSpacerItem|
   #:|insertSpacing|
   #:|insertStretch|
   #:|insertSubstitution.QFont|
   #:|insertSubstitutions.QFont|
   #:|insertTable|
   #:|insertTab|
   #:|insertText|
   #:|insertToolBarBreak|
   #:|insertToolBar|
   #:|insertTopLevelItems|
   #:|insertTopLevelItem|
   #:|insertWidget|
   #:|insert|
   #:|installEventFilter|
   #:|installFactory.QAccessible|
   #:|installNativeEventFilter|
   #:|installSceneEventFilter|
   #:|installTranslator.QCoreApplication|
   #:|installTranslatorFunctions|
   #:|instance.QCoreApplication|
   #:|instance|
   #:|intMaximum|
   #:|intMinimum|
   #:|intProperty|
   #:|intStep|
   #:|intValueChanged|
   #:|intValueSelected|
   #:|intValue|
   #:|intercept|
   #:|interfaceFromIndex.QNetworkInterface|
   #:|interfaceFromName.QNetworkInterface|
   #:|internalDelayedPopup|
   #:|internalTextureFormat|
   #:|interpretText|
   #:|intersected(QRect)|
   #:|intersected(QRegion)|
   #:|intersected|
   #:|intersects(QPainterPath)|
   #:|intersects(QRect)|
   #:|intersects(QRectF)|
   #:|intersects(QRegion)|
   #:|intersects|
   #:|interval|
   #:|invalidateContents|
   #:|invalidateFilter|
   #:|invalidateIndex|
   #:|invalidateSceneGraph|
   #:|invalidateScene|
   #:|invalidate|
   #:|invertPixels|
   #:|invertedAppearance|
   #:|invertedControls|
   #:|inverted|
   #:|invisibleRootItem|
   #:|invokeAction|
   #:|ip|
   #:|isAbsolutePath.QDir|
   #:|isAbsolute|
   #:|isAccelerated|
   #:|isAccepted(QGesture*)|
   #:|isAccepted(Qt::GestureType)|
   #:|isAccepted|
   #:|isActivated|
   #:|isActive.QAccessible|
   #:|isActiveWindow|
   #:|isActive|
   #:|isAffine|
   #:|isAmbiguous|
   #:|isAncestorOf|
   #:|isAnchor|
   #:|isAnimated|
   #:|isAnimating|
   #:|isAntennaConnected|
   #:|isAreaAllowed|
   #:|isArray|
   #:|isAtBoundary|
   #:|isAtlasTexture|
   #:|isAudioAvailable|
   #:|isAutoMipMapGenerationEnabled|
   #:|isAutoRepeat|
   #:|isAutoValue|
   #:|isAvailable|
   #:|isBackwardAvailable|
   #:|isBandSupported|
   #:|isBitmapScalable|
   #:|isBlacklisted|
   #:|isBlockFormat|
   #:|isBool|
   #:|isBound|
   #:|isBrushSet|
   #:|isBundle|
   #:|isCachingProxy|
   #:|isCallable|
   #:|isCaptureDestinationSupported|
   #:|isCaptureModeSupported|
   #:|isCharFormat|
   #:|isCheckable|
   #:|isChecked|
   #:|isClean|
   #:|isClearButtonEnabled|
   #:|isClipped|
   #:|isCollapsible|
   #:|isColorFilterSupported|
   #:|isColumnHidden|
   #:|isColumnSelected|
   #:|isComboBoxEditable|
   #:|isCommitPage|
   #:|isCompactMode|
   #:|isCompiled|
   #:|isComplete|
   #:|isComponentComplete|
   #:|isCompressed|
   #:|isContentEditable|
   #:|isContentSelected|
   #:|isCopyOf|
   #:|isCornerButtonEnabled|
   #:|isCosmetic|
   #:|isCreated|
   #:|isCreatingContents|
   #:|isCreatingIndex|
   #:|isDateEditEnabled|
   #:|isDate|
   #:|isDaylightTime|
   #:|isDebugBuild.QLibraryInfo|
   #:|isDefaultUp|
   #:|isDefault|
   #:|isDescending|
   #:|isDesignable|
   #:|isDirty|
   #:|isDir|
   #:|isDisabled|
   #:|isDockNestingEnabled|
   #:|isDown|
   #:|isDragEnabled|
   #:|isDriverAvailable.QSqlDatabase|
   #:|isDropEnabled|
   #:|isEditable|
   #:|isEffectEnabled.QApplication|
   #:|isEmpty|
   #:|isEnabledTo|
   #:|isEnabled|
   #:|isEqual|
   #:|isEquivalentTo|
   #:|isError|
   #:|isExclusive|
   #:|isExecutable|
   #:|isExpanded|
   #:|isExposed|
   #:|isExposureModeSupported|
   #:|isFile|
   #:|isFinalPage|
   #:|isFinished|
   #:|isFirstColumnSpanned|
   #:|isFirstItemColumnSpanned|
   #:|isFixedPitch|
   #:|isFixedSamplePositions|
   #:|isFlashModeSupported|
   #:|isFlashReady|
   #:|isFlat|
   #:|isFloatable|
   #:|isFloating|
   #:|isFocusModeSupported|
   #:|isFocusPointModeSupported|
   #:|isFocusScope|
   #:|isFormatSupported|
   #:|isForwardAvailable|
   #:|isForwardOnly|
   #:|isFrameFormat|
   #:|isFullScreen|
   #:|isGenerated(QString)|
   #:|isGenerated(int)|
   #:|isGenerated|
   #:|isGrayscale|
   #:|isGridVisible|
   #:|isGroupSeparatorShown|
   #:|isHeaderHidden|
   #:|isHidden|
   #:|isHttpOnly|
   #:|isIconVisibleInMenu|
   #:|isIdentifierEscaped|
   #:|isIdentity|))
